leafo/lapis

docs/configuration.md

Just a quick fix: the Configuration docs page was showing how to use `before_filter` to register an `after_dispatch` handler so perf data is output to the log. Though the correct syntax is `@before_filter => ...` (as `before_filter` is a function in `Application`), the page showed `@before_filter: =>` which did something else (overrode the local, inherited field of the class).
I've spent the last 30 minutes trying to figure out what was happening and went bug-hunting through the Lapis code---the colon was really easy to miss, and I'm a MoonScript/Lapis novice to boot. So I guess this, although minor, should be fixed to make life easier for somebody else :)

Fix a typo in configuration.md

---

docs/etlua_templates.md
docs/html_generation.md
docs/moon_getting_started.md

- In `docs/etlua_templates`, use `<%= url_for %>` instead of `<% url_for %>`.
- Fix a minor grammar issue in `docs/html_generation`.
- Address #292 in `docs/moon_getting_started`.

documentation fixes

---

lapis/validate.lua
lapis/validate.moon
spec/validate_spec.moon

Validation errors with keys!
When developing web applications/web services, etc is a common task to indicate that form elements or params have failed in data validation (without comparing string or whatever)
So using (notice 3rd parameter)
```moonscript
errors = validate o, {
{ "age", exists: true }
{ "name", exists: true }
{ "rupture", exists: true, "a custom message here" }
}, { key: true }
```
you can get something like this:
```moonscript
{
age: 'age must be provided',
rupture; 'a custom message here' 
}
```

validation now can show what fields have failed

---

docs/html_generation.md

"is prepended to" makes more sense than "is appended to the front of" and is less wordy.

Clarified wording in docs/html_generation.md

---

docs/testing.md

Mocking doesn't seem to allow ``ngx.req.read_body()`` and ``ngx.req.get_body_data()`` to work, and those two functions are the only way I've found that work to read the POST raw body (my POST requests both have the raw body and headers supplied).

Doc: test server is required for reading requests

---

lapis/db/mysql.lua
lapis/db/mysql.moon

I've added host and port to LuaSQL-mysql adapter to allow remote connections when running migrations. Sorry I couldn't add any specs related to this, let me know if you want it, then I can spend more time on it.

Allow migrations to run on remote mysql hosts

---

docs/moon_getting_started.md

"user.moon" where it should've been "users.moon"

typo fix in docs/moon_getting_started.md

---

docs/input_validation.md

"local app = lapis.Aplication()" where it should've been "local app = lapis.Application()"

fixed:typo fix in docs/input_validation.md

---

docs/models.md

typo in docs/models.md

---

docs/database.md

Added return in app.lua examples. For completeness sake. Otherwise results in internal server error if you forget to return the app object.

added return in app.lua examples

---

lapis/nginx.lua
lapis/nginx.moon

Corrected fix for https://github.com/leafo/lapis/issues/490

replace url\match in nginx.moon

---

docs/actions.md
docs/html_generation.md

Changed `app.<function> = function(self)` to `function app:<function>()` in actions.md
I hope I didn't miss anything :P

Some improvements to the documentation

---

lapis/cmd/templates/mime_types.moon

I don't know why these were even missing. An application written in lua/moonscript should know what lua/moonscript is, right? Every program should know their parents, right?

Added lua and moonscript mime types

---

lapis/db/base_model.moon

~~Fixes~~ *Should fix* bug described in #527
This could probably be simplified further into something like `return <value> or nil` but I don't moonscript, so I only did the most obvious thing.

Find method now *actually* returns nil instead of nothing at all

---

docs/database.md

This one tripped me up. I copy-pasted the code from the docs into the code and was wondering why I was getting `attempt to call global 'config' (a nil value)`.

docs: fix ambiguity for database config

---

docs/models.md

- "users" was used in a MoonScript example where "events" should have been.

Typo in Models documentation

---

lapis/db/postgres/schema.moon

Concurrent indexes are useful for large tables because they do not lock the table from writes.
I'm making this PR as a starting point. I'm happy add docs and test cases if this seems useful to others. 😄

Add Support for concurrent indexes on postgres

---

lapis/cmd/nginx/templates/config.lua
lapis/cmd/nginx/templates/config.moon

See [docs](https://github.com/openresty/lua-nginx-module#content_by_lua) for statement recommending users use `content_by_lua_block` instead.

Use content_by_lua_block in place of the discouraged content_by_lua

---

lapis/db/postgres.moon

If present, this will apply the `timeout` field in a Lapis postgres config block to the socket opened by pgmoon. This will technically also pass the same field to the constructor [here](https://github.com/leafo/pgmoon/blob/df9c974ecf9d4ba707594c483a2985ebf75eb900/pgmoon/init.moon#L155), but it's ignored there.

Add "timeout" config option for Postgres

---

docs/utilities.md

Documentation for `respond_to` had an invalid link to the section on Handling HTTP Verbs.

Fixed broken link in Utilities documentation

---

spec/cmd_spec.moon

I heard from an error message that I should install lposix, but I should actually install luaposix.

posix.setenv actually requires luaposix

---

docs/input_validation.md

> Tables are unpacked to allow multiple arguments to be specified, which means a single table cannot be passed as THE argument.
I was attempting to pass a hash table as an argument to a validation function, but as a table passed as an argument to a validation function is passed through `unpack`, my hash table was sent as zero arguments instead. I understand why it works this way, but it was frustrating to find out the hard way I could not do what I intended.

Clarify table limitation on custom validation functions
